# Generated by Django 3.2.7 on 2021-10-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='Hip Hop', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
